config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: :registrations}

  resources :tickets, except: [:edit, :update]

  namespace :admin do
    resources :railway_stations
    resources :routes
    resources :tickets
    resources :trains do
      resources :carriages, shallow: true
    end
  end

  get 'search' => 'search#index'
  get 'about' => 'about#index'

  root 'search#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  belongs_to :first_station, class_name: 'RailwayStation', foreign_key: :first_station_id
  belongs_to :last_station, class_name: 'RailwayStation', foreign_key: :last_station_id
  belongs_to :train
  belongs_to :user

  validates :user, :train, :first_station, :last_station, presence: true
  validates :passport_number, format: {with: /\A\d{3,10}\z/}
  validates :first_name, :last_name, format: {with: /\A[ _\-a-zа-я]{3,42}\z/i}
  validate :check_ticket

  after_create :send_notification

  def check_ticket
    errors.add(:base, I18n.t('admin.tickets.errors.uniq')) if first_station == last_station
  end

  def send_notification
    TicketMailer.buy_ticket(user, self).deliver_now
  end

end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :set_trains, only: [:new, :create, :edit, :update]
  before_action :set_users

  include TicketsHelper

  def index
    @tickets = Ticket.all
  end

  def show
    @ticket = get_ticket_params(@ticket.attributes.symbolize_keys, true)
    render 'tickets/show'
  end

  def new
    @ticket = Ticket.new
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      redirect_to admin_tickets_path
    else
      render :new
    end
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to admin_tickets_path
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to admin_tickets_path, notice: 'Ticket was successfully destroyed.'
  end

  private

  def set_users
    @users = User.all
  end

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def set_trains
    @trains = Train.all
  end

  def ticket_params
    params.require(:ticket).permit(:user_id, :first_name, :last_name, :passport_number,
                                   :train_id, :first_station_id, :last_station_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :destroy]

  include TicketsHelper

  def index
    @tickets = get_tickets_pre_params
  end

  def show
    @ticket = get_ticket_params(
        @ticket.attributes.symbolize_keys, true)
  end

  def new
    @full_params = get_ticket_params(choice_params, true)
    @ticket = Ticket.new
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    if @ticket.save
      redirect_to tickets_path
    else
      @full_params = get_ticket_params(ticket_params, true)
      render :new
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path, notice: 'Ticket was successfully destroyed.'
  end

  private

  def ticket_params
    params.require(:ticket).permit(:first_station_id, :last_station_id,
                                   :train_id, :first_name, :last_name,
                                   :passport_number)
  end

  def choice_params
    params.require(:choice).permit(:first_station_id, :last_station_id, :train_id)
  end

  def set_ticket
    @ticket = current_user.tickets.find(params[:id])
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper

  def get_ticket_params(params, full_info = false)
    stations = RailwayStation.find(params[:first_station_id], params[:last_station_id])
    params[:first_station_title] = stations[0].title
    params[:last_station_title] = stations[1].title
    train = Train.find(params[:train_id])
    params[:train_number] = train.number
    if full_info
      params[:departure] = train.route.railway_stations_routes.where(
          railway_station_id: params[:first_station_id]).first.departure
      params[:arrival] = train.route.railway_stations_routes.where(
          railway_station_id: params[:last_station_id]).first.arrival
      params[:route_name] = train.route.name
      params[:route_number] = train.route.number
    end
    params
  end

  def get_tickets_pre_params
    rezult = []
    current_user.tickets.each do |ticket|
      rezult << get_ticket_params(ticket.attributes.symbolize_keys)
    end
    rezult
  end

end

app/views/admin/tickets/_form.html.erb
<%= render 'common/errors', res: @ticket %>
<%= form_for @ticket, url: {action: action}, html: {class: 'form-style'} do |form| %>
    <ul>
      <li>
        <%= form.select :user_id, options_from_collection_for_select(
        @users, :id, :email, @ticket.user.present? ? @ticket.user.id : 0), {}, {class: 'select'} %>
        <%= form.select :train_id, options_from_collection_for_select(
        @trains, :id, :number, @ticket.train.present? ? @ticket.train.id : 0), {include_blank: t('admin.tickets.new.change_train')},
                    {onchange: 'render_stations_select_to_ticket()', id: :slc_trains, class: 'select'} %>
      </li>
      <li>
        <select name="ticket[first_station_id]" id='slc_first_station' , class="select" hidden>
        </select>
        <select name="ticket[last_station_id]" id='slc_last_station' , class="select" hidden>
        </select>
      </li>
      <li>
        <%= form.label :first_name %>
        <%= form.text_field :first_name, minlength: 3, maxlength: 25, required: true, class: 'field-style' %>
      </li>
      <li>
        <%= form.label :last_name %>
        <%= form.text_field :last_name, minlength: 3, maxlength: 25, required: true, class: 'field-style' %>
      </li>
      <li>
        <%= form.label :passport_number %>
        <%= form.number_field :passport_number, min: 0, required: true, class: 'field-style' %>
      </li>
      <li>
        <%= form.submit "#{@ticket.new_record? ? t('common.create') : t('common.edit')}" %>
      </li>
    </ul>
<% end %>

app/views/admin/tickets/_ticket.html.erb
<tr>
  <td><%= ticket.id %></td>
  <td><%= ticket.user.email %></td>
  <td><%= ticket.first_name + ' ' + ticket.last_name %></td>
  <td><%= link_to 'more_horiz', admin_ticket_path(ticket), class: 'material-icons button edit' %>
    <%= link_to 'edit', edit_admin_ticket_path(ticket), class: 'material-icons button edit' %>
    <%= link_to 'delete', admin_ticket_path(ticket), class: 'material-icons button delete', method: :delete, data: {confirm: t('common.confirm_del') } %></td>
</tr>

app/views/admin/tickets/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', action: :update %>
|
<%= link_to t('common.back'), admin_tickets_path, class: 'link-bt' %>

app/views/admin/tickets/index.html.erb
<h1><%= t('.title') %></h1>

<table class="flat-table">
  <thead>
  <tr>
    <th><%= t('.id') %></th>
    <th><%= t('.email') %></th>
    <th colspan="3"><%= t('.name') %></th>
  </tr>
  </thead>

  <tbody>
  <%= render @tickets %>
  </tbody>
</table>

<%= link_to t('common.back'), root_path, class: 'link-bt' %>

app/views/admin/tickets/new.html.erb
<h1><%= t('admin.tickets.new_ticket') %></h1>

<%= render 'form', action: :create %>

<%= link_to t('common.back'), admin_tickets_path, class: 'link-bt' %>