config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: :registrations}

  resources :tickets, except: [:edit, :update]

  namespace :admin do
    resources :railway_stations
    resources :routes
    resources :tickets
    resources :trains do
      resources :carriages, shallow: true
    end
  end

  get 'search' => 'search#index'
  get 'about' => 'about#index'

  root 'search#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carriage.rb
class Carriage < ApplicationRecord

  validates :bottom_places, :top_places, :side_bottom_places, :side_top_places, :sedentary_places,
            numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 80,
                           only_integer: true, allow_nil: true}

  belongs_to :train

end

app/controllers/admin/carriages_controller.rb
class Admin::CarriagesController < Admin::BaseController

  before_action :set_carriage, only: [:edit, :show, :update, :destroy]
  before_action :set_train, only: [:index, :new, :create]

  def index
    @carriages = @train.carriages
  end

  def show

  end

  def new
    @carriage = Carriage.new
  end

  def edit

  end


  def create
    @carriage = @train.carriages.new(carriage_params)
    if @carriage.save
      redirect_to admin_train_carriages_path
    else
      render :new
    end
  end

  def update
    if @carriage.update(carriage_params)
      redirect_to admin_train_carriages_path
    else
      render :edit
    end

  end

  def destroy
    train_id = @carriage.train_id
    @carriage.destroy
    redirect_to admin_train_carriages_path(train_id), notice: 'Train was successfully destroyed.'
  end

  private

  def set_train
    @train = Train.find(params[:train_id])
  end

  def set_carriage
    @carriage = Carriage.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def carriage_params
    params.require(:carriage).permit(:type, :top_places, :bottom_places,
                                     :side_top_places, :side_bottom_places, :sedentary_places)
  end

end

app/views/admin/carriages/_carriage.html.erb
<% if reverse %>
    <% @index ||= @train.carriages.count + 1 %>
    <% @index -= 1 %>
<% else %>
    <% @index ||= 0 %>
    <% @index += 1 %>
<% end %>
<td style="padding: 0"><%= link_to @index, admin_carriage_path(carriage),
                                   class: 'blue-btn', style: 'width: 100%; text-align: center' %></td>

app/views/admin/carriages/_carriage_detail.html.erb
<tr>
  <td><%= carriage_counter + 1%></td>
  <td><%= carriage.name %></td>
  <td><%= carriage.bottom_places %></td>
  <td><%= carriage.top_places %></td>
  <td><%= carriage.side_bottom_places %></td>
  <td><%= carriage.side_top_places %></td>
  <td><%= carriage.sedentary_places %></td>
  <td><%= link_to 'more_horiz', admin_carriage_path(carriage), class: 'material-icons button edit' %>
    <%= link_to 'delete', admin_carriage_path(carriage), class: 'material-icons button delete', method: :delete, data: {confirm: t('common.confirm_del') } %></td>
</tr>

app/views/admin/carriages/_form.html.erb
<%= render 'common/errors', res: @carriage %>
<%= form_for [:admin, @carriage], url: {action: action}, html: {class: 'form-style'} do |form| %>
    <ul>
      <% # принудительно зададим полям имена, т.к. юзаем sti и в случае ошибки валидации отрендериться уже класс-наследник %>
      <li>
        <%= form.select :type,
                        options_for_select([[t('admin.carriages.economy_name'), EconomyCarriage], [t('admin.carriages.coupe_name'), CoupeCarriage],
                                            [t('admin.carriages.spec_name'), SpecCarriage], [t('admin.carriages.sedentary_name'), SedentaryCarriage]], @carriage.type),
                        {include_blank: false},
                        {id: :carriage_type, onchange: 'HideFields(this)', name: 'carriage[type]', class: 'select'} %>
      <li>
        <table>
          <tr>
            <td><%= form.label :top_places %></td>
            <td><%= form.number_field :top_places, name: 'carriage[top_places]', class: 'field-style' %></td>
          </tr>
          <tr>
            <td><%= form.label :bottom_places %></td>
            <td><%= form.number_field :bottom_places, name: 'carriage[bottom_places]', class: 'field-style' %></td>
          </tr>
          <tr>
            <td><%= form.label :side_top_places %></td>
            <td><%= form.number_field :side_top_places, name: 'carriage[side_top_places]', class: 'field-style' %></td>
          </tr>
          <tr>
            <td><%= form.label :side_bottom_places %></td>
            <td><%= form.number_field :side_bottom_places, name: 'carriage[side_bottom_places]', class: 'field-style' %></td>
          <tr>
            <td><%= form.label :sedentary_places %></td>
            <td><%= form.number_field :sedentary_places, name: 'carriage[sedentary_places]', class: 'field-style' %></td>
          </tr>
        </table>
      <li>
        <%= form.submit "#{@carriage.new_record? ? t('common.create') : t('common.edit')}" %>
      </li>
    </ul>
<% end %>


<script type="text/javascript">
    $(function () {
        document.getElementById('carriage_type').onchange();
    });
</script>

app/views/admin/carriages/edit.html.erb
<h1><%= t('.title') %></h1>
<%= render 'form', action: :update %>
<%= link_to 'Назад', admin_train_carriages_path(@train), class: 'link-bt' %>

app/views/admin/carriages/index.html.erb
<h1><%= t('.title') + @train.number %></h1>
<table class="flat-table">
  <thead>
  <tr>
    <th><%= t('.number') %></th>
    <th><%= t('.type') %></th>
    <th><%= t('.bottom_places') %></th>
    <th><%= t('.top_places') %></th>
    <th><%= t('.side_bottom_places') %></th>
    <th><%= t('.side_top_places') %></th>
    <th><%= t('.sedentary_places') %></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <%= render partial: 'carriage_detail', collection: @carriages, as: :carriage %>
  </tbody>
</table>
<%= link_to t('common.back'), admin_trains_path, class: 'link-bt' %>
<%= link_to t('admin.carriages.new_carriage'), new_admin_train_carriage_path(@train), class: 'link-bt' %>

app/views/admin/carriages/new.html.erb
<h1><%= t('admin.carriages.new_carriage') %></h1>

<%= render 'form', action: :create %>

<%= link_to t('common.back'), admin_train_carriages_path(@train), class: 'link-bt' %>

app/views/admin/carriages/show.html.erb
<h1><%= t('.title') %></h1>
<table class="flat-table">
  <thead>
  <th><%= t('.type') %></th>
  <th><%= t('admin.carriages.index.bottom_places') %></th>
  <th><%= t('admin.carriages.index.top_places') %></th>
  <th><%= t('admin.carriages.index.side_bottom_places') %></th>
  <th><%= t('admin.carriages.index.side_top_places') %></th>
  <th><%= t('admin.carriages.index.sedentary_places') %></th>
  </thead>
  <tbody>
  <tr>
    <td><%= @carriage.name %></td>
    <td><%= @carriage.bottom_places %></td>
    <td><%= @carriage.top_places %></td>
    <td><%= @carriage.side_bottom_places %></td>
    <td><%= @carriage.side_top_places %></td>
    <td><%= @carriage.sedentary_places %></td>
  </tr>
  </tbody>
</table>
<%= link_to t('common.back'), admin_train_carriages_path(@train), class: 'link-bt' %>