config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: :registrations}

  resources :tickets, except: [:edit, :update]

  namespace :admin do
    resources :railway_stations
    resources :routes
    resources :tickets
    resources :trains do
      resources :carriages, shallow: true
    end
  end

  get 'search' => 'search#index'
  get 'about' => 'about#index'

  root 'search#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord

  validates :number, presence: true,
            uniqueness: true,
            format: {with: /\A\w{3,10}\z/i}

  belongs_to :route, optional: true
  belongs_to :railway_station, optional: true
  has_many :tickets
  has_many :carriages

  # находим поезда у которых в маршруте есть нужные станции
  def self.find_by_route_stations(params)
    rezult = []
    trains = Train.all
    stations = RailwayStation.find(params[:first_station], params[:last_station])
    trains.each do |train|
      next if train.route.nil?
      if train.route.railway_stations & stations == stations #если обе станции есть в маршруте
        #и станция отправления находится перед станцией назначения
        if train.route.railway_stations.index(stations[0]) < train.route.railway_stations.index(stations[1])
          rezult << train
        end
      end
    end
    rezult
  end

  def total_places(carriage_type, places_type)
    carriages.where(type: carriage_type).sum(places_type)
  end

end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
    respond_to do |format|
      format.html
      format.json do
        render json: Train.find(params[:id]).route_id
      end
    end
  end

  def new
    @routes = Route.all
    @train = Train.new
  end

  def edit
    @routes = Route.all
  end

  def create
    @train = Train.new(train_params)
      if @train.save
        redirect_to admin_trains_path
      else
        @routes = Route.all
        render :new
      end
  end

  def update
      if @train.update(train_params)
        redirect_to admin_trains_path
      else
        render :edit
      end
  end

  def destroy
    @train.destroy
    redirect_to admin_trains_path, notice: 'Train was successfully destroyed.'
  end

  private

    def set_train
      @routes = Route.all
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :route_id, :railway_station_id, :carriage_order)
    end

end

app/views/admin/trains/_form.html.erb
<%= render 'common/errors', res: @train %>
<%= form_for [:admin, @train], html: {class: 'form-style'} do |form| %>
    <ul>
      <li>
        <table>
          <tr>
            <td><%= form.label :number %></td>
            <td><%= form.label :route_id, 'Маршрут' %></td>
            <td><%= form.label :carriage_order %></td>
          </tr>
          <tr>
            <td><%= form.number_field :number, class: 'field-style', min: 1, max: 99999, required: true %></td>
            <% # генерим список маршрутов, в обработчике onchange которого js рендрящий радиобаттоны со станциями в маршруте %>
            <td><%= form.select :route_id, options_from_collection_for_select(@routes, :id, :number,
                                                                              @train.route.present? ? @train.route.id : 0), {include_blank: true},
                                {onchange: "render_stations_radiobuttons_to_train(\"#{admin_routes_path}\",
                      #{@train.railway_station.present? ? @train.railway_station.id : 0})", id: :slc_routes, class: 'select'} %></td>
            <td> <%= form.select :carriage_order,
                                 options_for_select([[t('.from_head'), true], [t('.from_tail'), false]],
                                                    @train.carriage_order), {}, {class: 'select'} %></td>
          </tr>
        </table>
      </li>
      <% # сюда будем рендерить радиобаттоны %>
      <li>
        <table id="route_stations">
        </table>
      </li>
      <li>
        <%= form.submit "#{@train.new_record? ? t('common.create') : t('common.edit')}" %>
      </li>
    </ul>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'more_horiz', [:admin, train], class: 'material-icons button edit' %>
    <%= link_to 'linear_scale', admin_train_carriages_path(train), class: 'material-icons button edit' %>
    <%= link_to 'edit', edit_admin_train_path(train), class: 'material-icons button edit' %>
    <%= link_to 'delete', [:admin, train], class: 'material-icons button delete', method: :delete, data: {confirm: t('common.confirm_del') } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>
<% # послезагрузки страницы отрендерим радиобатоны со станциями маршрута поезда %>
<script type="text/javascript">
    $(function() {
        document.getElementById('slc_routes').onchange();
    });
</script>

<%= link_to t('common.back'), admin_trains_path, class: 'link-bt' %>
<%= link_to t('common.show'), [:admin, @train], class: 'link-bt' %>

app/views/admin/trains/index.html.erb
<h1><%= t('.title') %></h1>

<table class="flat-table">
  <thead>
    <tr>
      <th><%= t('.train_number') %></th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to t('common.back'), root_path, class: 'link-bt' %>

app/views/admin/trains/new.html.erb
<h1><%= t('admin.trains.new_train') %></h1>

<%= render 'form' %>

<%= link_to t('common.back'), admin_trains_path, class: 'link-bt' %>

app/views/admin/trains/show.html.erb
<h1>Информация о поезде</h1>
<table class="flat-table">
  <thead>
  <th><%= t('admin.trains.index.train_number') %></th>
  <th colspan="2"><%= t('.route') %></th>
  <th><%= t('.corrent_station') %></th>
  </thead>
  <tbody>
  <tr>
    <td><%= @train.number %></td>
    <% if @train.route.present? %>
        <td><%= @train.route.number %></td>
        <td><%= @train.route.name %></td>
    <% end %>
    <td><%= @train.railway_station.present? ? @train.railway_station.title : 'N/A' %></td>
  </tr>
  </tbody>
</table>

<table class="flat-table">
  <thead>
  <th colspan="80"><%= t('.carriages') %></th>
  </thead>
  <tbody>
  <tr>
    <% if @train.carriage_order %>
        <%= render partial: 'admin/carriages/carriage', collection: @train.carriages,
                   locals: {reverse: false} %>
    <% else %>
        <%= render partial: 'admin/carriages/carriage', collection: @train.carriages.reverse,
                   locals: {reverse: true} %>
    <% end %>
  </tr>
  </tbody>
</table>

<%= link_to t('common.back'), admin_trains_path, class: 'link-bt' %>
<%= link_to t('common.edit'), edit_admin_train_path(@train), class: 'link-bt' %> |