config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: :registrations}

  resources :tickets, except: [:edit, :update]

  namespace :admin do
    resources :railway_stations
    resources :routes
    resources :tickets
    resources :trains do
      resources :carriages, shallow: true
    end
  end

  get 'search' => 'search#index'
  get 'about' => 'about#index'

  root 'search#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_menu.html.erb
<ul class="main-menu">
  <li><%= link_to t('.main'), root_path, class: 'root-item' %></li>
  <% if user_signed_in? %>
      <li><%= link_to t('.exit'), destroy_user_session_path, method: :delete, class: 'root-item' %></li>
      <li> <%= link_to t('.my_tickets'), tickets_path, class: 'root-item' %></li>
      <% if current_user.admin? %>
          <li>
            <%= link_to t('.stations'), admin_railway_stations_path, class: 'root-item' %>
            <ul>
              <li><%= link_to t('admin.railway_stations.create_station'), new_admin_railway_station_path %></li>
            </ul>
          </li>
          <li>
            <%= link_to t('.routes'), admin_routes_path, class: 'root-item' %>
            <ul>
              <li><%= link_to t('admin.routes.new_route'), new_admin_route_path %></li>
            </ul>
          </li>
          <li>
            <%= link_to t('.trains'), admin_trains_path, class: 'root-item' %>
            <ul>
              <li><%= link_to t('admin.trains.new_train'), new_admin_train_path %></li>
            </ul>
          </li>
          <li>
            <%= link_to t('.tickets'), admin_tickets_path, class: 'root-item' %>
            <ul>
              <li><%= link_to t('admin.tickets.new_ticket'), new_admin_ticket_path %></li>
            </ul>
          </li>
      <% end %>
  <% else %>
      <li><%= link_to t('.log_in'), new_user_session_path, class: 'root-item' %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railway</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon', type: 'image/x-icon' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<header>
  <%= render 'layouts/menu' %>
</header>
<main>
  <%= render 'common/flashes' %>
  <%= yield %>
</main>
<footer>
  <p>Samodelkin LTD</p>
</footer>
</body>
</html>